"""Seeded attack scenarios (spec §21).

Each scenario is a self-contained, realistic SOC case: raw-event summaries,
alerts, entities, evidence (labelled by epistemic kind), a timeline, competing
hypotheses, entity relationships, and a mapped response proposal. All of it is
DEMO-scoped and clearly simulated.

Scenarios are data, not code, so they are easy to review and extend. The
builder in :mod:`astrasoc.seed.engine` turns a definition into persisted rows
and wires evidence IDs into hypotheses and the timeline.
"""
from __future__ import annotations

# Epistemic-kind shorthands used below.
FACT = "confirmed_fact"
INFER = "model_inference"
ASSUMPTION = "assumption"
MISSING = "missing_evidence"

SCENARIOS: list[dict] = [
    {
        "key": "ransomware_precursor",
        "title": "Ransomware precursor: shadow-copy deletion on FIN-WKS-014",
        "severity": "critical", "confidence": 0.86, "business_risk": 88,
        "summary": "Endpoint FIN-WKS-014 executed vssadmin shadow-copy deletion and "
                   "bcdedit recovery tampering minutes after a suspicious archive "
                   "was written, a classic pre-encryption staging pattern.",
        "attack_tactics": ["Execution", "Defense Evasion", "Impact"],
        "attack_techniques": ["T1059.001", "T1490", "T1486", "T1486"],
        "entities": [
            {"kind": "host", "value": "FIN-WKS-014", "display": "Finance workstation 014",
             "criticality": "high", "risk": 92, "internal": True},
            {"kind": "user", "value": "acme\\jlaurent", "display": "Jean Laurent (Finance)",
             "criticality": "medium", "risk": 60, "internal": True},
            {"kind": "process", "value": "vssadmin.exe", "display": "vssadmin.exe delete shadows",
             "criticality": "low", "risk": 70, "internal": True},
            {"kind": "ip", "value": "185.220.101.42", "display": "185.220.101.42 (TOR exit)",
             "criticality": "low", "risk": 80, "internal": False},
            {"kind": "file", "value": "sha256:3f1c...a9", "display": "invoice_archive.7z",
             "criticality": "low", "risk": 65, "internal": True},
        ],
        "alerts": [
            {"title": "Volume shadow copies deleted via vssadmin", "severity": "critical",
             "source": "microsoft_defender", "techniques": ["T1490"], "confidence": 0.9,
             "desc": "vssadmin.exe delete shadows /all /quiet executed on FIN-WKS-014."},
            {"title": "Suspicious PowerShell download cradle", "severity": "high",
             "source": "crowdstrike_falcon", "techniques": ["T1059.001"], "confidence": 0.8,
             "desc": "Encoded PowerShell invoked Net.WebClient to external host."},
            {"title": "Outbound connection to TOR exit node", "severity": "medium",
             "source": "vectra", "techniques": ["T1090.003"], "confidence": 0.7,
             "desc": "FIN-WKS-014 connected to known TOR exit 185.220.101.42."},
        ],
        "evidence": [
            {"kind": FACT, "title": "vssadmin deletion command line", "confidence": 1.0,
             "source": "microsoft_defender", "techniques": ["T1490"],
             "content": "Process create: vssadmin.exe delete shadows /all /quiet "
                        "(parent powershell.exe, user acme\\jlaurent)."},
            {"kind": FACT, "title": "Encoded PowerShell execution", "confidence": 1.0,
             "source": "crowdstrike_falcon", "techniques": ["T1059.001"],
             "content": "powershell.exe -nop -w hidden -enc <base64> decoding to a "
                        "Net.WebClient download cradle."},
            {"kind": FACT, "title": "TOR egress connection", "confidence": 0.95,
             "source": "vectra", "techniques": ["T1090.003"],
             "content": "TCP 443 to 185.220.101.42, matched against TOR exit list."},
            {"kind": INFER, "title": "Pre-encryption staging in progress", "confidence": 0.82,
             "source": "sim-investigator-1",
             "content": "Shadow-copy deletion + recovery tampering + external cradle is "
                        "consistent with ransomware staging before encryption."},
            {"kind": MISSING, "title": "No encryption/ransom note observed yet", "confidence": 0.0,
             "source": "analyst",
             "content": "No file-encryption bursts or ransom note detected. Encryption may "
                        "not have started — containment window is open."},
        ],
        "timeline": [
            {"offset_min": -42, "title": "invoice_archive.7z written to Downloads",
             "category": "event", "techniques": []},
            {"offset_min": -18, "title": "Encoded PowerShell download cradle executed",
             "category": "event", "techniques": ["T1059.001"], "evidence": 1},
            {"offset_min": -9, "title": "Outbound TOR connection established",
             "category": "event", "techniques": ["T1090.003"], "evidence": 2},
            {"offset_min": -2, "title": "Shadow copies deleted via vssadmin",
             "category": "event", "techniques": ["T1490"], "evidence": 0},
            {"offset_min": 0, "title": "Incident created by correlation engine",
             "category": "event", "techniques": []},
        ],
        "hypotheses": [
            {"statement": "Human-operated ransomware is staging FIN-WKS-014 for encryption.",
             "is_primary": True, "confidence": 0.82, "techniques": ["T1486", "T1490"],
             "supporting": [0, 1, 2, 3],
             "missing": ["Encryption activity / ransom note", "Lateral movement to file servers"]},
            {"statement": "A red-team exercise is generating the activity.",
             "is_primary": False, "confidence": 0.12,
             "supporting": [], "missing": ["Authorized test window record"]},
        ],
        "relationships": [(1, 0, "logged_into"), (0, 3, "connected_to"), (2, 0, "executed_on"),
                          (0, 4, "wrote_file")],
        "recommended_action": {"action": "isolate_endpoint", "target_entity": 0,
                               "confidence": 0.86, "reversible": True},
    },
    {
        "key": "identity_compromise",
        "title": "Impossible travel + MFA fatigue on m.okafor",
        "severity": "high", "confidence": 0.8, "business_risk": 74,
        "summary": "Sign-ins for m.okafor originate from two continents within 22 "
                   "minutes, preceded by a burst of MFA push notifications (fatigue).",
        "attack_tactics": ["Initial Access", "Credential Access"],
        "attack_techniques": ["T1078", "T1621", "T1110"],
        "entities": [
            {"kind": "user", "value": "m.okafor@acme.io", "display": "Miriam Okafor (Sales Dir)",
             "criticality": "high", "risk": 78, "internal": True},
            {"kind": "ip", "value": "41.203.72.9", "display": "41.203.72.9 (Lagos, NG)",
             "criticality": "low", "risk": 72, "internal": False},
            {"kind": "ip", "value": "72.229.28.185", "display": "72.229.28.185 (New York, US)",
             "criticality": "low", "risk": 20, "internal": False},
        ],
        "alerts": [
            {"title": "Impossible travel detected", "severity": "high", "source": "entra_id",
             "techniques": ["T1078"], "confidence": 0.85,
             "desc": "Sign-ins from Lagos and New York 22 minutes apart."},
            {"title": "MFA fatigue: repeated push denials then approval", "severity": "high",
             "source": "entra_id", "techniques": ["T1621"], "confidence": 0.78,
             "desc": "9 MFA push prompts in 4 minutes; final prompt approved."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Two sign-ins, disjoint geographies", "confidence": 1.0,
             "source": "entra_id", "techniques": ["T1078"],
             "content": "Successful interactive sign-in 41.203.72.9 (Lagos) 09:58Z and "
                        "72.229.28.185 (New York) 09:36Z — travel physically impossible."},
            {"kind": FACT, "title": "MFA push burst", "confidence": 1.0, "source": "entra_id",
             "techniques": ["T1621"],
             "content": "9 push challenges 09:52-09:56Z, denied x8 then approved."},
            {"kind": INFER, "title": "Credentials likely phished/replayed", "confidence": 0.76,
             "source": "sim-investigator-1",
             "content": "MFA-fatigue + foreign sign-in indicates valid credential possession "
                        "by an attacker; account likely compromised."},
            {"kind": MISSING, "title": "No malicious mailbox rule confirmed", "confidence": 0.0,
             "source": "analyst",
             "content": "Have not yet checked for inbox rules / OAuth grants that would "
                        "confirm post-compromise persistence."},
        ],
        "timeline": [
            {"offset_min": -22, "title": "Baseline sign-in from New York (expected)",
             "category": "event", "evidence": 0},
            {"offset_min": -6, "title": "MFA push burst begins", "category": "event",
             "techniques": ["T1621"], "evidence": 1},
            {"offset_min": -2, "title": "Sign-in from Lagos succeeds", "category": "event",
             "techniques": ["T1078"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "m.okafor's account is compromised via MFA-fatigue credential replay.",
             "is_primary": True, "confidence": 0.76, "techniques": ["T1078", "T1621"],
             "supporting": [0, 1, 2],
             "missing": ["Persistence mechanism (inbox rule / OAuth grant)"]},
            {"statement": "User is travelling with a VPN causing a false geo signal.",
             "is_primary": False, "confidence": 0.18, "supporting": [],
             "missing": ["Corporate VPN log correlation"]},
        ],
        "relationships": [(0, 1, "authenticated_from"), (0, 2, "authenticated_from")],
        "recommended_action": {"action": "revoke_sessions", "target_entity": 0,
                               "confidence": 0.8, "reversible": True},
    },
    {
        "key": "password_spraying",
        "title": "Password spray against VPN portal, one success",
        "severity": "high", "confidence": 0.72, "business_risk": 66,
        "summary": "1,842 failed auths across 210 accounts from a small IP set, "
                   "followed by one successful login to svc-backup.",
        "attack_tactics": ["Credential Access", "Initial Access"],
        "attack_techniques": ["T1110.003", "T1078"],
        "entities": [
            {"kind": "account", "value": "svc-backup", "display": "svc-backup (service acct)",
             "criticality": "high", "risk": 70, "internal": True},
            {"kind": "ip", "value": "45.155.205.233", "display": "45.155.205.233 (hosting)",
             "criticality": "low", "risk": 68, "internal": False},
        ],
        "alerts": [
            {"title": "Password spray pattern on VPN", "severity": "high", "source": "splunk",
             "techniques": ["T1110.003"], "confidence": 0.8,
             "desc": "High failure ratio across many accounts, low per-account attempts."},
            {"title": "Successful auth after spray", "severity": "high", "source": "splunk",
             "techniques": ["T1078"], "confidence": 0.7,
             "desc": "svc-backup authenticated successfully from spray source IP."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Spray failure distribution", "confidence": 1.0,
             "source": "splunk", "techniques": ["T1110.003"],
             "content": "1,842 4625 events, 210 distinct accounts, 3 source IPs over 11 min."},
            {"kind": FACT, "title": "svc-backup success from spray IP", "confidence": 1.0,
             "source": "splunk", "techniques": ["T1078"],
             "content": "4624 logon for svc-backup from 45.155.205.233 at 03:14Z."},
            {"kind": INFER, "title": "Service account credential guessed", "confidence": 0.68,
             "source": "sim-investigator-1",
             "content": "Weak/unrotated service credential most likely guessed during spray."},
        ],
        "timeline": [
            {"offset_min": -14, "title": "Spray begins", "category": "event",
             "techniques": ["T1110.003"], "evidence": 0},
            {"offset_min": -1, "title": "svc-backup login succeeds", "category": "event",
             "techniques": ["T1078"], "evidence": 1},
        ],
        "hypotheses": [
            {"statement": "svc-backup was compromised via password spray.", "is_primary": True,
             "confidence": 0.68, "techniques": ["T1110.003", "T1078"], "supporting": [0, 1, 2],
             "missing": ["Post-login activity of svc-backup"]},
        ],
        "relationships": [(0, 1, "authenticated_from")],
        "recommended_action": {"action": "disable_account", "target_entity": 0,
                               "confidence": 0.72, "reversible": True},
    },
    {
        "key": "c2_beaconing",
        "title": "Periodic C2 beaconing from ENG-LT-233",
        "severity": "high", "confidence": 0.78, "business_risk": 62,
        "summary": "Regular 60s ± 3s JA3-consistent HTTPS beacons to a low-reputation "
                   "domain with uniform small payloads.",
        "attack_tactics": ["Command and Control"],
        "attack_techniques": ["T1071.001", "T1573"],
        "entities": [
            {"kind": "host", "value": "ENG-LT-233", "display": "Engineering laptop 233",
             "criticality": "medium", "risk": 74, "internal": True},
            {"kind": "domain", "value": "cdn-metrics-sync.com", "display": "cdn-metrics-sync.com",
             "criticality": "low", "risk": 82, "internal": False},
        ],
        "alerts": [
            {"title": "Beaconing: regular interval C2", "severity": "high", "source": "vectra",
             "techniques": ["T1071.001"], "confidence": 0.82,
             "desc": "60s ± 3s beacon to cdn-metrics-sync.com, uniform payload size."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Beacon periodicity", "confidence": 0.95, "source": "vectra",
             "techniques": ["T1071.001"],
             "content": "312 connections, interval mean 60.2s, stdev 2.9s, payload 428±12 bytes."},
            {"kind": FACT, "title": "Domain reputation", "confidence": 0.9, "source": "virustotal",
             "content": "cdn-metrics-sync.com registered 6 days ago, 4/89 vendors flag malicious."},
            {"kind": INFER, "title": "Implant beaconing to C2", "confidence": 0.78,
             "source": "sim-investigator-1",
             "content": "Low-jitter periodicity + newly-registered low-rep domain indicates "
                        "an implant beaconing to C2."},
            {"kind": MISSING, "title": "Implant binary not yet identified", "confidence": 0.0,
             "source": "analyst",
             "content": "Process responsible for the beacon not yet pinned via EDR."},
        ],
        "timeline": [
            {"offset_min": -180, "title": "First beacon observed", "category": "event",
             "techniques": ["T1071.001"], "evidence": 0},
            {"offset_min": 0, "title": "Beaconing alert raised", "category": "event"},
        ],
        "hypotheses": [
            {"statement": "ENG-LT-233 is running a C2 implant.", "is_primary": True,
             "confidence": 0.78, "techniques": ["T1071.001"], "supporting": [0, 1, 2],
             "missing": ["Responsible process/binary"]},
            {"statement": "Benign telemetry/SaaS agent with periodic sync.", "is_primary": False,
             "confidence": 0.2, "supporting": [], "missing": ["Allowlist confirmation"]},
        ],
        "relationships": [(0, 1, "connected_to")],
        "recommended_action": {"action": "block_domain", "target_entity": 1,
                               "confidence": 0.78, "reversible": True},
    },
    {
        "key": "dns_tunneling",
        "title": "DNS tunneling via high-entropy subdomains",
        "severity": "medium", "confidence": 0.7, "business_risk": 54,
        "summary": "Sustained TXT queries with high-entropy labels to a single "
                   "authoritative domain, indicative of DNS-based exfil/C2.",
        "attack_tactics": ["Command and Control", "Exfiltration"],
        "attack_techniques": ["T1071.004", "T1048"],
        "entities": [
            {"kind": "host", "value": "HR-WKS-051", "display": "HR workstation 051",
             "criticality": "medium", "risk": 60, "internal": True},
            {"kind": "domain", "value": "sync.telemetry-cdn.net", "display": "sync.telemetry-cdn.net",
             "criticality": "low", "risk": 76, "internal": False},
        ],
        "alerts": [
            {"title": "DNS tunneling suspected", "severity": "medium", "source": "elastic",
             "techniques": ["T1071.004"], "confidence": 0.72,
             "desc": "High-entropy TXT queries, 40+/min to one domain."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Query entropy + volume", "confidence": 0.92, "source": "elastic",
             "techniques": ["T1071.004"],
             "content": "2,400 TXT queries in 60m, mean label entropy 4.1 bits/char to "
                        "*.sync.telemetry-cdn.net."},
            {"kind": INFER, "title": "DNS tunnel for C2/exfil", "confidence": 0.7,
             "source": "sim-investigator-1",
             "content": "Entropy and cadence match DNS tunneling toolkits."},
        ],
        "timeline": [
            {"offset_min": -60, "title": "Tunneling pattern begins", "category": "event",
             "techniques": ["T1071.004"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "HR-WKS-051 exfiltrates/receives C2 over DNS.", "is_primary": True,
             "confidence": 0.7, "techniques": ["T1071.004", "T1048"], "supporting": [0, 1],
             "missing": ["Decoded tunnel content", "Endpoint process attribution"]},
        ],
        "relationships": [(0, 1, "connected_to")],
        "recommended_action": {"action": "block_domain", "target_entity": 1,
                               "confidence": 0.7, "reversible": True},
    },
    {
        "key": "cloud_key_exposure",
        "title": "AWS access key exposed and used from new geography",
        "severity": "high", "confidence": 0.83, "business_risk": 80,
        "summary": "An IAM access key committed to a public repo was used from an "
                   "unfamiliar ASN to enumerate S3 and create a new access key.",
        "attack_tactics": ["Initial Access", "Persistence", "Discovery"],
        "attack_techniques": ["T1078.004", "T1552.001", "T1580"],
        "entities": [
            {"kind": "cloud_resource", "value": "AKIA5X...QT", "display": "IAM key AKIA5X...QT (ci-deployer)",
             "criticality": "critical", "risk": 90, "internal": True},
            {"kind": "ip", "value": "103.152.36.7", "display": "103.152.36.7 (SG hosting)",
             "criticality": "low", "risk": 74, "internal": False},
        ],
        "alerts": [
            {"title": "Access key used from new ASN", "severity": "high", "source": "aws",
             "techniques": ["T1078.004"], "confidence": 0.85,
             "desc": "ci-deployer key used from unfamiliar ASN, no prior history."},
            {"title": "New IAM access key created", "severity": "high", "source": "aws",
             "techniques": ["T1098.001"], "confidence": 0.8,
             "desc": "CreateAccessKey for ci-deployer from same session."},
        ],
        "evidence": [
            {"kind": FACT, "title": "CloudTrail: foreign key use", "confidence": 1.0, "source": "aws",
             "techniques": ["T1078.004"],
             "content": "GetCallerIdentity + ListBuckets from 103.152.36.7, sourceIP never "
                        "seen for this principal in 90d."},
            {"kind": FACT, "title": "CloudTrail: CreateAccessKey", "confidence": 1.0, "source": "aws",
             "techniques": ["T1098.001"],
             "content": "CreateAccessKey issued for ci-deployer during the same session."},
            {"kind": FACT, "title": "Key found in public commit", "confidence": 0.9,
             "source": "misp", "techniques": ["T1552.001"],
             "content": "Matching AKIA prefix found in a public GitHub commit 2 days ago."},
            {"kind": INFER, "title": "Credential leaked then abused", "confidence": 0.83,
             "source": "sim-investigator-1",
             "content": "Leaked CI key is being used by an external actor establishing "
                        "persistence via a new key."},
        ],
        "timeline": [
            {"offset_min": -2880, "title": "Key committed to public repo", "category": "event",
             "techniques": ["T1552.001"], "evidence": 2},
            {"offset_min": -35, "title": "Key used from Singapore ASN", "category": "event",
             "techniques": ["T1078.004"], "evidence": 0},
            {"offset_min": -20, "title": "New access key created", "category": "event",
             "techniques": ["T1098.001"], "evidence": 1},
        ],
        "hypotheses": [
            {"statement": "Leaked ci-deployer key is being abused to establish persistence.",
             "is_primary": True, "confidence": 0.83,
             "techniques": ["T1078.004", "T1098.001", "T1552.001"], "supporting": [0, 1, 2, 3],
             "missing": ["Full blast radius of S3 access", "Data staged for exfil?"]},
        ],
        "relationships": [(0, 1, "used_from")],
        "recommended_action": {"action": "disable_account", "target_entity": 0,
                               "confidence": 0.83, "reversible": True},
    },
    {
        "key": "phishing_attachment",
        "title": "Phishing with malicious macro attachment (12 recipients)",
        "severity": "high", "confidence": 0.79, "business_risk": 58,
        "summary": "A spoofed-invoice email with a macro-laden .xlsm reached 12 "
                   "mailboxes; two users opened it and one enabled macros.",
        "attack_tactics": ["Initial Access", "Execution"],
        "attack_techniques": ["T1566.001", "T1204.002", "T1059.005"],
        "entities": [
            {"kind": "mailbox", "value": "ap-team@acme.io", "display": "Accounts Payable DL",
             "criticality": "medium", "risk": 55, "internal": True},
            {"kind": "domain", "value": "acme-invoices.com", "display": "acme-invoices.com (lookalike)",
             "criticality": "low", "risk": 80, "internal": False},
            {"kind": "file", "value": "sha256:9ba2...7d", "display": "Invoice_04821.xlsm",
             "criticality": "low", "risk": 78, "internal": True},
        ],
        "alerts": [
            {"title": "Phishing email with macro attachment", "severity": "high",
             "source": "microsoft_defender", "techniques": ["T1566.001"], "confidence": 0.82,
             "desc": "Lookalike sender domain, macro .xlsm, 12 recipients."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Sender domain is a lookalike", "confidence": 1.0,
             "source": "microsoft_defender", "techniques": ["T1566.001"],
             "content": "From acme-invoices.com registered 3 days ago; not an Acme domain."},
            {"kind": FACT, "title": "Macro downloads second stage", "confidence": 0.9,
             "source": "virustotal", "techniques": ["T1059.005"],
             "content": "Static analysis: AutoOpen macro fetches payload from external host."},
            {"kind": FACT, "title": "One user enabled macros", "confidence": 1.0,
             "source": "microsoft_defender", "techniques": ["T1204.002"],
             "content": "EXCEL.EXE spawned WScript on one recipient host."},
            {"kind": INFER, "title": "Active phishing intrusion attempt", "confidence": 0.79,
             "source": "sim-investigator-1",
             "content": "Weaponized document executed on at least one host — likely foothold."},
        ],
        "timeline": [
            {"offset_min": -50, "title": "Email delivered to 12 mailboxes", "category": "event",
             "techniques": ["T1566.001"], "evidence": 0},
            {"offset_min": -12, "title": "Macro enabled; WScript spawned", "category": "event",
             "techniques": ["T1204.002"], "evidence": 2},
        ],
        "hypotheses": [
            {"statement": "Phishing campaign achieved code execution on one host.",
             "is_primary": True, "confidence": 0.79,
             "techniques": ["T1566.001", "T1204.002", "T1059.005"], "supporting": [0, 1, 2, 3],
             "missing": ["Second-stage payload identity", "C2 established?"]},
        ],
        "relationships": [(0, 1, "received_from"), (2, 0, "attached_to")],
        "recommended_action": {"action": "quarantine_email", "target_entity": 0,
                               "confidence": 0.79, "reversible": True},
    },
    {
        "key": "lateral_movement",
        "title": "Lateral movement via SMB + PsExec from patient zero",
        "severity": "high", "confidence": 0.75, "business_risk": 71,
        "summary": "Admin share writes and service creation on three servers trace "
                   "back to a single compromised workstation.",
        "attack_tactics": ["Lateral Movement", "Execution"],
        "attack_techniques": ["T1021.002", "T1570", "T1569.002"],
        "entities": [
            {"kind": "host", "value": "IT-WKS-002", "display": "IT workstation 002 (patient zero)",
             "criticality": "medium", "risk": 84, "internal": True},
            {"kind": "host", "value": "SRV-APP-01", "display": "Application server 01",
             "criticality": "high", "risk": 70, "internal": True},
            {"kind": "host", "value": "SRV-DB-02", "display": "Database server 02",
             "criticality": "critical", "risk": 76, "internal": True},
        ],
        "alerts": [
            {"title": "Admin share write + service creation", "severity": "high",
             "source": "crowdstrike_falcon", "techniques": ["T1021.002", "T1569.002"],
             "confidence": 0.78, "desc": "ADMIN$ writes then service create on SRV-APP-01/DB-02."},
        ],
        "evidence": [
            {"kind": FACT, "title": "ADMIN$ file writes", "confidence": 1.0,
             "source": "crowdstrike_falcon", "techniques": ["T1570", "T1021.002"],
             "content": "PsExeSvc.exe written to ADMIN$ on SRV-APP-01 and SRV-DB-02 from IT-WKS-002."},
            {"kind": FACT, "title": "Service creation events", "confidence": 1.0,
             "source": "crowdstrike_falcon", "techniques": ["T1569.002"],
             "content": "7045 service install for PSEXESVC on both servers."},
            {"kind": INFER, "title": "Hands-on-keyboard lateral movement", "confidence": 0.75,
             "source": "sim-investigator-1",
             "content": "PsExec pattern from one source to multiple servers indicates operator "
                        "moving laterally toward the DB tier."},
        ],
        "timeline": [
            {"offset_min": -25, "title": "ADMIN$ write to SRV-APP-01", "category": "event",
             "techniques": ["T1021.002"], "evidence": 0},
            {"offset_min": -18, "title": "Service install on SRV-APP-01", "category": "event",
             "techniques": ["T1569.002"], "evidence": 1},
            {"offset_min": -6, "title": "ADMIN$ write to SRV-DB-02", "category": "event",
             "techniques": ["T1021.002"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "Operator is moving laterally from IT-WKS-002 toward the DB tier.",
             "is_primary": True, "confidence": 0.75,
             "techniques": ["T1021.002", "T1570", "T1569.002"], "supporting": [0, 1, 2],
             "missing": ["Credentials/technique used to authenticate", "Objective on SRV-DB-02"]},
        ],
        "relationships": [(0, 1, "moved_to"), (0, 2, "moved_to")],
        "recommended_action": {"action": "isolate_endpoint", "target_entity": 0,
                               "confidence": 0.75, "reversible": True},
    },
    {
        "key": "data_exfiltration",
        "title": "Large outbound transfer to personal cloud storage",
        "severity": "high", "confidence": 0.7, "business_risk": 77,
        "summary": "4.2 GB uploaded from a finance host to a consumer file-sharing "
                   "service after business hours.",
        "attack_tactics": ["Collection", "Exfiltration"],
        "attack_techniques": ["T1074", "T1567.002"],
        "entities": [
            {"kind": "host", "value": "FIN-WKS-009", "display": "Finance workstation 009",
             "criticality": "high", "risk": 72, "internal": True},
            {"kind": "domain", "value": "mega-upload-sync.io", "display": "mega-upload-sync.io",
             "criticality": "low", "risk": 66, "internal": False},
            {"kind": "user", "value": "acme\\rpatel", "display": "Rohan Patel (Finance)",
             "criticality": "medium", "risk": 58, "internal": True},
        ],
        "alerts": [
            {"title": "Anomalous large upload to consumer storage", "severity": "high",
             "source": "stellar_cyber", "techniques": ["T1567.002"], "confidence": 0.72,
             "desc": "4.2 GB egress to mega-upload-sync.io at 23:41 local."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Egress volume + destination", "confidence": 0.95,
             "source": "stellar_cyber", "techniques": ["T1567.002"],
             "content": "4.2 GB over HTTPS to mega-upload-sync.io, 60x this host's daily baseline."},
            {"kind": FACT, "title": "Prior local staging", "confidence": 0.85, "source": "elastic",
             "techniques": ["T1074"],
             "content": "Large archive assembled in %TEMP% 20 minutes before upload."},
            {"kind": INFER, "title": "Data exfiltration in progress/complete", "confidence": 0.7,
             "source": "sim-investigator-1",
             "content": "Off-hours staging + bulk upload to consumer storage indicates exfil."},
            {"kind": ASSUMPTION, "title": "Assumed sensitive financial data", "confidence": 0.4,
             "source": "analyst",
             "content": "Assuming the archive contained finance data given host role; not yet "
                        "confirmed by DLP content inspection."},
        ],
        "timeline": [
            {"offset_min": -20, "title": "Archive staged in TEMP", "category": "event",
             "techniques": ["T1074"], "evidence": 1},
            {"offset_min": 0, "title": "4.2 GB uploaded", "category": "event",
             "techniques": ["T1567.002"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "Finance data is being exfiltrated to personal cloud storage.",
             "is_primary": True, "confidence": 0.7, "techniques": ["T1074", "T1567.002"],
             "supporting": [0, 1, 2], "missing": ["DLP content classification of the archive"]},
            {"statement": "Legitimate large personal backup by the user.", "is_primary": False,
             "confidence": 0.25, "supporting": [], "missing": ["User statement / policy exception"]},
        ],
        "relationships": [(0, 1, "connected_to"), (2, 0, "logged_into")],
        "recommended_action": {"action": "block_domain", "target_entity": 1,
                               "confidence": 0.7, "reversible": True},
    },
    {
        "key": "malicious_powershell",
        "title": "Obfuscated PowerShell with AMSI bypass",
        "severity": "high", "confidence": 0.77, "business_risk": 60,
        "summary": "Heavily obfuscated PowerShell attempted an AMSI bypass and "
                   "reflectively loaded a .NET assembly in memory.",
        "attack_tactics": ["Execution", "Defense Evasion"],
        "attack_techniques": ["T1059.001", "T1562.001", "T1620"],
        "entities": [
            {"kind": "host", "value": "MKT-WKS-118", "display": "Marketing workstation 118",
             "criticality": "low", "risk": 68, "internal": True},
            {"kind": "process", "value": "powershell.exe", "display": "Obfuscated PowerShell",
             "criticality": "low", "risk": 72, "internal": True},
        ],
        "alerts": [
            {"title": "AMSI bypass + reflective load", "severity": "high",
             "source": "microsoft_defender", "techniques": ["T1562.001", "T1620"],
             "confidence": 0.8, "desc": "AmsiScanBuffer patch attempt then in-memory assembly load."},
        ],
        "evidence": [
            {"kind": FACT, "title": "AMSI bypass string", "confidence": 0.95,
             "source": "microsoft_defender", "techniques": ["T1562.001"],
             "content": "Script content references [Ref].Assembly...amsiInitFailed pattern."},
            {"kind": FACT, "title": "Reflective assembly load", "confidence": 0.9,
             "source": "crowdstrike_falcon", "techniques": ["T1620"],
             "content": "System.Reflection.Assembly::Load called on a byte array (no file on disk)."},
            {"kind": INFER, "title": "Fileless payload execution", "confidence": 0.77,
             "source": "sim-critic-1",
             "content": "AMSI tampering + reflective load is fileless malware tradecraft."},
        ],
        "timeline": [
            {"offset_min": -3, "title": "Obfuscated PowerShell executed", "category": "event",
             "techniques": ["T1059.001"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "Fileless malware executed on MKT-WKS-118.", "is_primary": True,
             "confidence": 0.77, "techniques": ["T1059.001", "T1562.001", "T1620"],
             "supporting": [0, 1, 2], "missing": ["Loaded assembly identity / C2"]},
        ],
        "relationships": [(1, 0, "executed_on")],
        "recommended_action": {"action": "collect_endpoint_evidence", "target_entity": 0,
                               "confidence": 0.77, "reversible": True},
    },
    {
        "key": "insider_risk",
        "title": "Insider risk: bulk CRM export before resignation",
        "severity": "medium", "confidence": 0.62, "business_risk": 63,
        "summary": "A departing sales rep exported the full customer database and "
                   "copied it to removable media.",
        "attack_tactics": ["Collection", "Exfiltration"],
        "attack_techniques": ["T1074", "T1052.001"],
        "entities": [
            {"kind": "user", "value": "acme\\dkowalski", "display": "Dana Kowalski (Sales, notice)",
             "criticality": "medium", "risk": 66, "internal": True},
            {"kind": "host", "value": "SAL-WKS-077", "display": "Sales workstation 077",
             "criticality": "low", "risk": 50, "internal": True},
        ],
        "alerts": [
            {"title": "Bulk CRM export + USB write", "severity": "medium", "source": "elastic",
             "techniques": ["T1052.001"], "confidence": 0.65,
             "desc": "Full account export followed by 1.1 GB copy to removable media."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Full CRM export event", "confidence": 1.0, "source": "elastic",
             "content": "CRM audit: export-all-accounts by dkowalski (18,402 records)."},
            {"kind": FACT, "title": "USB mass-storage write", "confidence": 1.0,
             "source": "microsoft_defender", "techniques": ["T1052.001"],
             "content": "1.1 GB written to removable volume E: within 4 minutes of export."},
            {"kind": ASSUMPTION, "title": "Assumed malicious intent (on notice period)",
             "confidence": 0.4, "source": "analyst",
             "content": "User is on notice; intent inferred but not confirmed. Could be "
                        "legitimate handover."},
        ],
        "timeline": [
            {"offset_min": -8, "title": "CRM full export", "category": "event", "evidence": 0},
            {"offset_min": -3, "title": "Copy to USB", "category": "event",
             "techniques": ["T1052.001"], "evidence": 1},
        ],
        "hypotheses": [
            {"statement": "Departing employee is exfiltrating customer data to USB.",
             "is_primary": True, "confidence": 0.62, "techniques": ["T1074", "T1052.001"],
             "supporting": [0, 1, 2], "missing": ["HR/manager confirmation of policy breach"]},
            {"statement": "Sanctioned data handover for account transition.", "is_primary": False,
             "confidence": 0.3, "supporting": [], "missing": ["Approved handover ticket"]},
        ],
        "relationships": [(0, 1, "logged_into")],
        "recommended_action": {"action": "create_ticket", "target_entity": 0,
                               "confidence": 0.62, "reversible": True},
    },
    {
        "key": "vuln_exploitation",
        "title": "Exploitation of internet-facing service (CVE-2023-XXXX)",
        "severity": "critical", "confidence": 0.81, "business_risk": 85,
        "summary": "A public web server was exploited via a known deserialization "
                   "CVE, yielding a web shell and outbound callback.",
        "attack_tactics": ["Initial Access", "Persistence"],
        "attack_techniques": ["T1190", "T1505.003"],
        "entities": [
            {"kind": "host", "value": "DMZ-WEB-03", "display": "DMZ web server 03",
             "criticality": "high", "risk": 88, "internal": True},
            {"kind": "vulnerability", "value": "CVE-2023-34362", "display": "CVE-2023-34362 (deserialization RCE)",
             "criticality": "critical", "risk": 95, "internal": True},
            {"kind": "ip", "value": "194.26.29.156", "display": "194.26.29.156 (attacker)",
             "criticality": "low", "risk": 84, "internal": False},
        ],
        "alerts": [
            {"title": "Exploitation attempt on public service", "severity": "critical",
             "source": "microsoft_sentinel", "techniques": ["T1190"], "confidence": 0.85,
             "desc": "Deserialization payload to DMZ-WEB-03 matching CVE-2023-34362."},
            {"title": "Web shell written to webroot", "severity": "critical",
             "source": "crowdstrike_falcon", "techniques": ["T1505.003"], "confidence": 0.8,
             "desc": "New .aspx file in webroot spawned cmd.exe."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Exploit payload in request", "confidence": 0.95,
             "source": "microsoft_sentinel", "techniques": ["T1190"],
             "content": "POST with serialized gadget chain to /moveit; server returned 200."},
            {"kind": FACT, "title": "Web shell file + child process", "confidence": 1.0,
             "source": "crowdstrike_falcon", "techniques": ["T1505.003"],
             "content": "human2.aspx written to webroot; w3wp.exe spawned cmd.exe."},
            {"kind": FACT, "title": "Outbound callback", "confidence": 0.9, "source": "vectra",
             "content": "DMZ-WEB-03 initiated outbound TCP to 194.26.29.156 post-exploit."},
            {"kind": INFER, "title": "Server compromised via CVE, web shell planted",
             "confidence": 0.81, "source": "sim-investigator-1",
             "content": "Exploit + web shell + callback confirm a successful RCE and persistence."},
        ],
        "timeline": [
            {"offset_min": -12, "title": "Exploit request received", "category": "event",
             "techniques": ["T1190"], "evidence": 0},
            {"offset_min": -9, "title": "Web shell written", "category": "event",
             "techniques": ["T1505.003"], "evidence": 1},
            {"offset_min": -7, "title": "Outbound callback", "category": "event", "evidence": 2},
        ],
        "hypotheses": [
            {"statement": "DMZ-WEB-03 is compromised via CVE-2023-34362 with a web shell.",
             "is_primary": True, "confidence": 0.81, "techniques": ["T1190", "T1505.003"],
             "supporting": [0, 1, 2, 3], "missing": ["Extent of post-exploit activity"]},
        ],
        "relationships": [(2, 0, "exploited"), (0, 1, "affected_by")],
        "recommended_action": {"action": "isolate_endpoint", "target_entity": 0,
                               "confidence": 0.81, "reversible": True},
    },
    {
        "key": "suspicious_ldap",
        "title": "Suspicious LDAP reconnaissance (BloodHound-style)",
        "severity": "medium", "confidence": 0.66, "business_risk": 57,
        "summary": "A workstation issued thousands of LDAP queries enumerating "
                   "users, groups and ACLs — classic AD recon.",
        "attack_tactics": ["Discovery"],
        "attack_techniques": ["T1087.002", "T1069.002", "T1482"],
        "entities": [
            {"kind": "host", "value": "ENG-WKS-045", "display": "Engineering workstation 045",
             "criticality": "medium", "risk": 64, "internal": True},
            {"kind": "user", "value": "acme\\svc-scan", "display": "svc-scan",
             "criticality": "medium", "risk": 60, "internal": True},
        ],
        "alerts": [
            {"title": "High-volume LDAP enumeration", "severity": "medium", "source": "microsoft_defender",
             "techniques": ["T1087.002"], "confidence": 0.68,
             "desc": "3,900 LDAP searches enumerating users/groups/ACLs in 5 min."},
        ],
        "evidence": [
            {"kind": FACT, "title": "LDAP query burst", "confidence": 0.95,
             "source": "microsoft_defender", "techniques": ["T1087.002", "T1069.002"],
             "content": "3,900 LDAP searches for objectClass user/group + ACL reads from ENG-WKS-045."},
            {"kind": INFER, "title": "AD attack-path mapping", "confidence": 0.66,
             "source": "sim-investigator-1",
             "content": "Query pattern matches BloodHound/SharpHound collection."},
        ],
        "timeline": [
            {"offset_min": -5, "title": "LDAP enumeration burst", "category": "event",
             "techniques": ["T1087.002"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "An attacker is mapping AD attack paths from ENG-WKS-045.",
             "is_primary": True, "confidence": 0.66,
             "techniques": ["T1087.002", "T1069.002", "T1482"], "supporting": [0, 1],
             "missing": ["Tool/process attribution", "Whether results were exfiltrated"]},
            {"statement": "Authorized vulnerability scanner (svc-scan) activity.", "is_primary": False,
             "confidence": 0.3, "supporting": [], "missing": ["Change ticket for scan window"]},
        ],
        "relationships": [(1, 0, "logged_into")],
        "recommended_action": {"action": "increase_monitoring", "target_entity": 0,
                               "confidence": 0.66, "reversible": True},
    },
    {
        "key": "ioc_firewall_match",
        "title": "IOC match: allowed vs denied firewall traffic to known-bad IP",
        "severity": "high", "confidence": 0.74, "business_risk": 64,
        "summary": "Threat-intel IOC 88.119.169.20 matched firewall logs — some "
                   "connections were denied, but two were ALLOWED before the block.",
        "attack_tactics": ["Command and Control"],
        "attack_techniques": ["T1071", "T1219"],
        "entities": [
            {"kind": "ip", "value": "88.119.169.20", "display": "88.119.169.20 (malware C2, MISP)",
             "criticality": "low", "risk": 86, "internal": False},
            {"kind": "host", "value": "OPS-WKS-020", "display": "Operations workstation 020",
             "criticality": "medium", "risk": 62, "internal": True},
        ],
        "alerts": [
            {"title": "Allowed traffic to known-bad IOC", "severity": "high", "source": "generic_syslog",
             "techniques": ["T1071"], "confidence": 0.76,
             "desc": "2 ALLOWED sessions to 88.119.169.20 before firewall rule blocked the rest."},
        ],
        "evidence": [
            {"kind": FACT, "title": "IOC/firewall correlation", "confidence": 0.95,
             "source": "misp", "techniques": ["T1071"],
             "content": "88.119.169.20 present in MISP (malware C2). Firewall: 2 ALLOW, 47 DENY "
                        "for OPS-WKS-020 in the last hour."},
            {"kind": INFER, "title": "Two successful C2 sessions before block", "confidence": 0.74,
             "source": "sim-investigator-1",
             "content": "The two ALLOWED sessions may have carried C2; endpoint should be triaged."},
            {"kind": MISSING, "title": "Content of allowed sessions unknown", "confidence": 0.0,
             "source": "analyst",
             "content": "No packet capture for the two allowed sessions; can't confirm payload."},
        ],
        "timeline": [
            {"offset_min": -58, "title": "First ALLOWED session to IOC", "category": "event",
             "techniques": ["T1071"], "evidence": 0},
            {"offset_min": -40, "title": "Firewall rule blocks further traffic", "category": "action",
             "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "OPS-WKS-020 briefly communicated with a known C2 before blocking.",
             "is_primary": True, "confidence": 0.74, "techniques": ["T1071", "T1219"],
             "supporting": [0, 1], "missing": ["Payload of allowed sessions", "Endpoint implant"]},
        ],
        "relationships": [(1, 0, "connected_to")],
        "recommended_action": {"action": "block_ip", "target_entity": 0,
                               "confidence": 0.74, "reversible": True},
    },
    {
        "key": "privileged_misuse",
        "title": "Privileged account misuse: off-hours domain admin activity",
        "severity": "high", "confidence": 0.68, "business_risk": 79,
        "summary": "A Domain Admin account performed group-membership changes and "
                   "DC access at 03:00 from a non-admin workstation.",
        "attack_tactics": ["Privilege Escalation", "Persistence"],
        "attack_techniques": ["T1078.002", "T1098"],
        "entities": [
            {"kind": "account", "value": "acme\\da-hkim", "display": "da-hkim (Domain Admin)",
             "criticality": "critical", "risk": 82, "internal": True},
            {"kind": "host", "value": "ENG-WKS-088", "display": "Engineering workstation 088",
             "criticality": "medium", "risk": 58, "internal": True},
        ],
        "alerts": [
            {"title": "Off-hours Domain Admin group change", "severity": "high", "source": "entra_id",
             "techniques": ["T1098"], "confidence": 0.7,
             "desc": "da-hkim added an account to Domain Admins at 03:07 from a workstation."},
        ],
        "evidence": [
            {"kind": FACT, "title": "Group membership change", "confidence": 1.0, "source": "active_directory",
             "techniques": ["T1098"],
             "content": "4728: member added to Domain Admins by da-hkim at 03:07Z."},
            {"kind": FACT, "title": "Admin logon from non-admin host", "confidence": 1.0,
             "source": "active_directory", "techniques": ["T1078.002"],
             "content": "da-hkim interactive logon on ENG-WKS-088 (not a PAW)."},
            {"kind": INFER, "title": "Privileged account possibly misused/compromised",
             "confidence": 0.68, "source": "sim-investigator-1",
             "content": "Off-hours privileged change from a standard workstation is anomalous."},
            {"kind": MISSING, "title": "No change ticket correlated", "confidence": 0.0,
             "source": "analyst",
             "content": "No approved change record found for this membership change yet."},
        ],
        "timeline": [
            {"offset_min": -20, "title": "da-hkim logon on ENG-WKS-088", "category": "event",
             "techniques": ["T1078.002"], "evidence": 1},
            {"offset_min": -13, "title": "Domain Admins membership changed", "category": "event",
             "techniques": ["T1098"], "evidence": 0},
        ],
        "hypotheses": [
            {"statement": "Domain Admin credentials are being misused for persistence.",
             "is_primary": True, "confidence": 0.68, "techniques": ["T1078.002", "T1098"],
             "supporting": [0, 1, 2], "missing": ["Change-management correlation", "Owner confirmation"]},
        ],
        "relationships": [(0, 1, "logged_into")],
        "recommended_action": {"action": "revoke_sessions", "target_entity": 0,
                               "confidence": 0.68, "reversible": True},
    },
]

SCENARIO_INDEX = {s["key"]: s for s in SCENARIOS}
