{{- $name := include "astrasoc.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-web
  labels: {{- include "astrasoc.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: web }
  template:
    metadata:
      labels: {{- include "astrasoc.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: web
          image: "{{ .Values.image.registry }}/{{ .Values.web.repository }}:{{ include "astrasoc.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ name: http, containerPort: {{ .Values.web.port }} }]
          env:
            - name: API_INTERNAL_URL
              value: "http://{{ $name }}-api:{{ .Values.api.port }}"
          readinessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 20
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
      {{- with .Values.web.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-web
  labels: {{- include "astrasoc.labels" . | nindent 4 }}
spec:
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: web }
  ports: [{ name: http, port: {{ .Values.web.port }}, targetPort: http }]
