"""mssp hierarchy and platform hardening

Adds the MSSP tenant hierarchy (kind, parent, status, tier, region, SLA,
contacts, branding, contract), delegated access grants, usage metering,
shift handovers, SLA breach bookkeeping, notification delivery tracking,
session binding / refresh rotation, account lockout, provider daily token
budgets and the keyed audit chain (seq). Existing rows receive safe
server defaults; audit rows written before this migration are marked
chain_version=1 (legacy, unkeyed).

Revision ID: 006c58caeaa0
Revises: 3e397dfac37e
Create Date: 2026-09-26 12:41:13.454667
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (JSONB variant)
import astrasoc.db  # noqa: F401 (GUID/JSON types)
from sqlalchemy.dialects import postgresql

revision = '006c58caeaa0'
down_revision = '3e397dfac37e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_handovers',
    sa.Column('provider_tenant_id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('author_id', astrasoc.db.GUID(length=36), nullable=True),
    sa.Column('author_label', sa.String(length=200), nullable=False),
    sa.Column('shift', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('open_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged_by', astrasoc.db.GUID(length=36), nullable=True),
    sa.Column('acknowledged_at', astrasoc.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('created_at', astrasoc.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', astrasoc.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_tenant_id'], ['tenants.id'], name=op.f('fk_shift_handovers_provider_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_handovers'))
    )
    with op.batch_alter_table('shift_handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_handovers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_handovers_provider_tenant_id'), ['provider_tenant_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('tenant_id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('created_at', astrasoc.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', astrasoc.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_usage_counters_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_counters')),
    sa.UniqueConstraint('tenant_id', 'period', 'metric', name='uq_usage_tenant_period_metric')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counters_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counters_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counters_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_access_grants',
    sa.Column('provider_tenant_id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('customer_tenant_id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('user_id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_by', astrasoc.db.GUID(length=36), nullable=True),
    sa.Column('expires_at', astrasoc.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', astrasoc.db.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', astrasoc.db.GUID(length=36), nullable=False),
    sa.Column('created_at', astrasoc.db.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', astrasoc.db.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_tenant_id'], ['tenants.id'], name=op.f('fk_tenant_access_grants_customer_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_tenant_id'], ['tenants.id'], name=op.f('fk_tenant_access_grants_provider_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_access_grants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_access_grants'))
    )
    with op.batch_alter_table('tenant_access_grants', schema=None) as batch_op:
        batch_op.create_index('ix_grants_user_customer', ['user_id', 'customer_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_access_grants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_access_grants_customer_tenant_id'), ['customer_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_access_grants_provider_tenant_id'), ['provider_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_access_grants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chain_version', sa.Integer(), nullable=False, server_default=sa.text("'1'")))
        batch_op.create_index(batch_op.f('ix_audit_events_seq'), ['seq'], unique=True)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_ack_breached_at', astrasoc.db.TZDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sla_resolve_breached_at', astrasoc.db.TZDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('escalation_level', sa.Integer(), nullable=False, server_default=sa.text("'0'")))

    with op.batch_alter_table('model_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_today', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('tokens_day', sa.String(length=10), nullable=False, server_default=sa.text("''")))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=False, server_default=sa.text("'in_app'")))
        batch_op.add_column(sa.Column('recipient', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=False, server_default=sa.text("'not_requested'")))
        batch_op.add_column(sa.Column('delivery_detail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subject_tenant_id', astrasoc.db.GUID(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_subject_tenant_id'), ['subject_tenant_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('previous_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_used_at', astrasoc.db.TZDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('revoked_reason', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_previous_token_hash'), ['previous_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_sid'), ['sid'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), nullable=False, server_default=sa.text("'customer'")))
        batch_op.add_column(sa.Column('parent_id', astrasoc.db.GUID(length=36), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False, server_default=sa.text("'active'")))
        batch_op.add_column(sa.Column('service_tier', sa.String(length=24), nullable=False, server_default=sa.text("'professional'")))
        batch_op.add_column(sa.Column('region', sa.String(length=16), nullable=False, server_default=sa.text("'global'")))
        batch_op.add_column(sa.Column('sla_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('contacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('branding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('contract_start', astrasoc.db.TZDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('contract_end', astrasoc.db.TZDateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenants_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_status'), ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tenants_parent_id_tenants'), 'tenants', ['parent_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('locked_until', astrasoc.db.TZDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', astrasoc.db.TZDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tenants_parent_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tenants_status'))
        batch_op.drop_index(batch_op.f('ix_tenants_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_kind'))
        batch_op.drop_column('contract_end')
        batch_op.drop_column('contract_start')
        batch_op.drop_column('branding')
        batch_op.drop_column('contacts')
        batch_op.drop_column('sla_policy')
        batch_op.drop_column('region')
        batch_op.drop_column('service_tier')
        batch_op.drop_column('status')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('kind')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_sid'))
        batch_op.drop_index(batch_op.f('ix_sessions_previous_token_hash'))
        batch_op.drop_column('revoked_reason')
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('previous_token_hash')
        batch_op.drop_column('sid')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_subject_tenant_id'))
        batch_op.drop_column('subject_tenant_id')
        batch_op.drop_column('delivery_detail')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('recipient')
        batch_op.drop_column('channel')

    with op.batch_alter_table('model_providers', schema=None) as batch_op:
        batch_op.drop_column('tokens_day')
        batch_op.drop_column('tokens_today')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('escalation_level')
        batch_op.drop_column('sla_resolve_breached_at')
        batch_op.drop_column('sla_ack_breached_at')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_seq'))
        batch_op.drop_column('chain_version')
        batch_op.drop_column('seq')

    with op.batch_alter_table('tenant_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_access_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_access_grants_provider_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_access_grants_customer_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_access_grants_created_at'))
        batch_op.drop_index('ix_grants_user_customer')

    op.drop_table('tenant_access_grants')
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_counters_period'))
        batch_op.drop_index(batch_op.f('ix_usage_counters_metric'))
        batch_op.drop_index(batch_op.f('ix_usage_counters_created_at'))

    op.drop_table('usage_counters')
    with op.batch_alter_table('shift_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_handovers_provider_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_shift_handovers_created_at'))

    op.drop_table('shift_handovers')
    # ### end Alembic commands ###
